const list = [
    {
      id: 1,
      title: "The Great Disappearance: 31 Ways to be Rapture Ready",
      author: "David Jeremiah | October 2023",
      price: 20,
      img: "https://m.media-amazon.com/images/I/71RxwXoyOFL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "The Wager: A Tale of Shipwreck, Mutiny and Murder",
      author: "David Grann  | 18 April 2023",
      price: 15,
      img: "https://m.media-amazon.com/images/I/91qXDU9TXvL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "House of Leaves: The Remastered Full-Color Edition",
      author: " Mark Z. Danielewski  | 7 March 2020",
      price: 14,
      img: "https://m.media-amazon.com/images/I/810pcXb+l3L._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Behind A Closed Door",
      author: "by Wonder House Books | 13 May 2024",
      price: 27,
      img: "https://m.media-amazon.com/images/I/71djhi7ul3L._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Never Lie: An addictive psychological thriller",
      author: "Freida McFadden  | 15 September 2022",
      price: 9,
      img: "https://m.media-amazon.com/images/I/61UdOEvyVjL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Wrong Place Wrong Time: A Reese's Book Club Pick",
      author: "Gillian McAllister  | 23 May 2023",
      price: 4,
      img: "https://m.media-amazon.com/images/I/81pOIaiJRUL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "You Like It Darker: Stories",
      author: "Stephen King  | 21 May 2024",
      price: 28,
      img: "https://m.media-amazon.com/images/I/71fjILT8ZoL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "The Inmate: A gripping psychological thriller",
      author: "Freida McFadden  | 13 June 2022",
      price: 12,
      img: "https://m.media-amazon.com/images/I/61AMZwoowaL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "The Love of My Life: A GMA Book Club Pick (A Novel) ",
      author: "Rosie Walsh | 7 January 2023",
      price: 3,
      img: "https://m.media-amazon.com/images/I/91BfSqEcRdL._AC_UY436_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Brain Activity Book for Kids",
      author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Willy the Silly Panda",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Grandma's Bag of Stories",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
  ];
  
  export default list;
  